# site settings
title: Purshottam Shivraj
subtitle: Personal Webpage
email: shivrajpurshottam@gmail.com
description: Data Scientist | Resercher | Kaggle Master
baseurl: "/" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address:
city: Seattle
state: WA
zip_code: 98105
country: United States of America

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url: https://github.com/pshivraj
gitlab_url:
googleplus_url:
#instagram_url: https://instagram.com
linkedin_url: https://www.linkedin.com/in/shivrajp/
pinterest_url:
slack_url:
#twitter_url: https://twitter.com/Vedant_C6

# build settings
markdown: kramdown

sass:
  style: compressed
